---
title: "Generation of LRIs; Fig,ure 5.1 and Suppl. File 7"
author: "Aram Safrastyan"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: TRUE
    code_folding: hide
    number_sections: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# load libraries
***

```{r, pkgs, message=F, warning=F}
# load libraries
devtools::install_github("jcolinge/BulkSignalR@v0.0.9")
devtools::install_github("saezlab/liana")
remotes::install_version("matrixStats", version="1.1.0", repos = "http://cran.us.r-project.org")
library(SingleR)
library(parallel)
library(doParallel)
library(Seurat)
library(liana)
library(data.table)
library(scran)
library(BulkSignalR)
library(tidyverse)
library(pheatmap)
library(UpSetR)
library(ggvenn)
library(scales)
library(circlize)
library(openxlsx)
library(cowplot)
library(viridis)
library(ggpubr)
```

# LRIs in cell-free transcriptome
***

```{r, cfLRIs, fig.width= 15, fig.height=8, warning = T, message = T, eval = T}
# Chen et al., 2022 aka elife dataset LRIs; generated with code of Chapter 4
load("./data/cfinput_clean_all.RData")
# set the number of processors to use
n.proc <- snakemake@threads
cl <- makeCluster(n.proc)
registerDoParallel(cl)
# determine the ligand-receptor interactions per biological condition and export the results
for (i in unique(elife_meta_all$cond)) {
  elife_samples <- elife_meta_all %>%
    dplyr::filter(cond == i) %>%
    dplyr::pull(samples)
  elife_df <- elife_countm_all %>%
    as.data.frame() %>%
    dplyr::select(elife_samples)
  # follow the canonical steps of the Bisque package
  bsrdm <- prepareDataset(counts = elife_df)
  bsrdm <- learnParameters(bsrdm)
  bsrinf <- initialInference(bsrdm)
  save(bsrdm, bsrinf, file = paste0("./data/", i, ".RData"))
}

# Zhu et al., 2021 aka therano dataset LRIs; same steps; generated with the code of Chapter 4
## load data
load("./data/cfinput_clean_filt.RData")
## do the analysis separateyl for healthy donors and liver cancer samples
## liver cancer
therano_hcc <- therano_countm[, 1:35]
bsrdm <- prepareDataset(counts = therano_hcc)
bsrdm_therano_hcc <- learnParameters(bsrdm)
bsrinf_therano_hcc <- initialInference(bsrdm_therano_hcc)
## healthy donors
therano_nc <- therano_countm[, 36:65]
bsrdm <- prepareDataset(counts = therano_nc)
bsrdm_therano_nc <- learnParameters(bsrdm)
bsrinf_therano_nc <- initialInference(bsrdm_therano_nc)
# save the results
save(bsrdm_therano_hcc, bsrinf_therano_hcc, bsrdm_therano_nc, bsrinf_therano_nc, file = "./data/therano_lrp.RData")
```

#  Download the data (scRNA-seq)
***

```{bash scdownload, message=F, warning=F, eval=T}
#download the reference scRNA-seq count matrix
wget -q -O - https://ftp.ncbi.nlm.nih.gov/geo/series/GSE115nnn/GSE115469/suppl/GSE115469_Data.csv.gz | gunzip -c > ./data/GSE115469_Data.csv
#download the reference metadata
wget -q -O - https://ftp.ncbi.nlm.nih.gov/geo/series/GSE115nnn/GSE115469/suppl/GSE115469_CellClusterType.txt.gz | gunzip -c > ./data/GSE115469_CellClusterType.txt
#download the liver cancer scRNA-seq count matrix
wget -q -O - https://ftp.ncbi.nlm.nih.gov/geo/series/GSE149nnn/GSE149614/suppl/GSE149614_HCC.scRNAseq.S71915.count.txt.gz | gunzip -c > ./data/GSE149614_HCC.scRNAseq.S71915.count.txt
#download the liver cancer scRNA-seq metadata
wget -q -O - https://ftp.ncbi.nlm.nih.gov/geo/series/GSE149nnn/GSE149614/suppl/GSE149614_HCC.metadata.updated.txt.gz | gunzip -c > ./data/GSE149614_HCC.metadata.txt
```

# LRIs in scRNA-seq dataset
***

```{r, scLRIs, fig.width= 15, fig.height=8, warning = F, message = F, eval = T}
# select tumor samples with HBV to bring to closer to the cfRNA samples
hcc_metadata <- read.delim("./data/GSE149614_HCC.metadata.txt")
hcc_hbv <- hcc_metadata %>% dplyr::filter(site == "Tumor" & virus == "HBV")
hcc_sc <- fread("./data/GSE149614_HCC.scRNAseq.S71915.count.txt")
hcc_sc_hbv <- hcc_sc %>% dplyr::select(V1, hcc_hbv$Cell)
hcc_sc_hbv <- hcc_sc_hbv %>% column_to_rownames(var = "V1")
hcc_sc_hbv <- as.matrix(hcc_sc_hbv)
# annotate the cell types by using a reference scRNA-seq dataset
ref_annot <- read.delim("./data/GSE115469_CellClusterType.txt")
ref_countm <- read.csv("./data/GSE115469_Data.csv")
# collapse the cell type annotations for more streamlined analysis in line with previous sections
ref_annot$CellType <- ifelse(grepl("Hepatocyte", ref_annot$CellType), "Hepatocyte", ref_annot$CellType)
ref_annot$CellType <- ifelse(grepl("T_Cells", ref_annot$CellType), "T_Cells", ref_annot$CellType)
ref_annot$CellType <- ifelse(grepl("LSECs", ref_annot$CellType), "LSECs", ref_annot$CellType)
ref_annot$CellType <- ifelse(grepl("Macrophage", ref_annot$CellType), "Macrophage", ref_annot$CellType)
ref_countm <- ref_countm %>%
  column_to_rownames(., var = "X") %>%
  as.matrix()
# annotation
hcc_hbv_annot <- SingleR(test = hcc_sc_hbv, ref = ref_countm, labels = ref_annot$CellType, de.method = "wilcox")
# LRI detection
seurat_object <- CreateSeuratObject(counts = hcc_sc_hbv)
seurat_object <- AddMetaData(seurat_object, hcc_hbv$sample, col.name = "sample")
seurat_object <- AddMetaData(seurat_object, hcc_hbv$stage, col.name = "stage")
seurat_object <- AddMetaData(seurat_object, hcc_hbv_annot$labels, col.name = "celltype")
seurat_object <- SetIdent(seurat_object, value = "celltype")
seurat_object <- NormalizeData(seurat_object)
# export 
save(seurat_object, file = "./data/hbv_sc_seurat.RData")
liana_raw <- liana_wrap(seurat_object, resource = c("LRdb"))
liana_raw <- liana_raw %>%
  liana_aggregate()
liana_raw <- liana_raw %>% dplyr::mutate(lr = paste0(ligand.complex, "_", receptor.complex))
# export
save(liana_raw, file = "./data/hbv_liana_lrdb.RData")
```

#  Download the data (bulk RNA-seq)
***

```{bash bulk_download, message=F, warning=F, eval=T}
#download the count matrix
wget -q -O - https://ftp.ncbi.nlm.nih.gov/geo/series/GSE124nnn/GSE124535/suppl/GSE124535_HCC.RNA-seq.35.samples.fpkm.txt.gz | gunzip -c > ./data/GSE124535_HCC.RNA-seq.35.samples.fpkm.txt
```

# LRIs in bulk RNA-seq dataset
***

```{r, bulk_lri, fig.width= 15, fig.height=8, warning = F, message = F, error=F, eval = T}
# load data
liver_gse <- read.delim("./data/GSE124535_HCC.RNA-seq.35.samples.fpkm.txt")
# cleanup
liver_gse <- liver_gse %>% dplyr::select(-c(1, 3:4))
liver_gse_filt <- liver_gse[rowMeans(liver_gse[, -1]) > 0, ]
liver_gse_filt <- liver_gse_filt %>%
  distinct(gene_symbol, .keep_all = TRUE) %>%
  column_to_rownames(var = "gene_symbol")
# choose the HCC samples
liver_gse_hcc <- liver_gse_filt %>% dplyr::select(36:70)
# LRI detection
bsrdm_hcc <- prepareDataset(counts = liver_gse_hcc, normalize = FALSE, method = "TC") # the data is already normalized
bsrdm_hcc <- learnParameters(bsrdm_hcc)
bsrinf_hcc <- initialInference(bsrdm_hcc)
# export
save(bsrdm_hcc, bsrinf_hcc, file = "./data/gse_liver_res.RData")
```

# Figure 5.1
***

```{r, fig5_1, fig.width= 15, fig.height=8, warning = F, message = F, eval = T}
# load Chen et al., 2022/elife LRIs and choose significant LRIs
load("./data/ESCA.RData")
esca_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/HD.RData")
hd_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/LUAD.RData")
luad_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/STAD.RData")
stad_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/CRC.RData")
crc_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
load("./data/LC.RData")
lc_LR <- LRinter(bsrinf) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
rm(bsrdm, bsrinf, scoresPathway)

# upset plot
upset_list <- list(ESCA = esca_LR$lr, HD = hd_LR$lr, LC = lc_LR$lr, STAD = stad_LR$lr, LUAD = luad_LR$lr, CRC = crc_LR$lr)
ups_plot <- upset(fromList(upset_list), order.by = "freq", nsets = 10, nintersects = 10, text.scale = 2)
uu_c <- cowplot::plot_grid(NULL, ups_plot$Main_bar, ups_plot$Sizes, ups_plot$Matrix,
  nrow = 2, align = "hv", rel_heights = c(3, 1),
  rel_widths = c(2, 5)
)

# load Zhu et al., 2021/therano LRIs and choose significant LRIs
load("./data/therano_lrp.RData")
hcc_therano <- LRinter(bsrinf_therano_hcc) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)
nc_therano <- LRinter(bsrinf_therano_nc) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001)

# venn diagram
venn_input <- list(
  `LC (Chen et al., 2022)` = lc_LR$lr,
  `LC (Zhu et al., 2021)` = hcc_therano$lr
)
elife_th_venn <- ggvenn(venn_input, auto_scale = T, text_size = 4, set_name_size = 5)

# create fig and export
fig5_1 <- ggdraw() +
  draw_plot(uu_c, x = 0, y = 0, width = .95, height = 1) +
  draw_plot(elife_th_venn, x = 0.6, y = 0.45, width = .3, height = 0.5) +
  draw_plot_label(label = c("A", "B"), size = 18, x = c(0.2, 0.6), y = c(1, 1), family = "Arial")
dir.create("./figs/")
fig5_1
```

# Suppl. File 7
***

```{r, suppl_file7, fig.width= 15, fig.height=8, warning = T, message = T, eval = T}
# load the sc and bulk LRIs
# load scRNA-seq LRIs and choose significant LRIs
load("./data/hbv_liana_lrdb.RData")
lc_sc <- liana_raw %>%
  dplyr::mutate(lr = paste0(ligand.complex, "_", receptor.complex)) %>%
  dplyr::filter(cellphonedb.pvalue < 0.05 & sca.LRscore >= 0.5)

# load bulk RNA-seq LRIs and choose significant LRIs
load("./data/gse_liver_res.RData")
lc_bulk <- LRinter(bsrinf_hcc) %>%
  dplyr::mutate(lr = paste0(L, "_", R)) %>%
  dplyr::filter(qval < 0.001 & LR.corr >= 0.5)

list_of_datasets <- list("LC LRIs (Chen et al., 2022)" = lc_LR, "HD LRIs (Chen et al., 2022)" = hd_LR, "LC LRIs (Zhu et al., 2021)" = hcc_therano, "HD LRIs (Zhu et al., 2021)" = nc_therano, "LC LRIs (Bulk)" = lc_bulk, "LC LRIs (SC)" = lc_sc, "ESCA LRIs" = esca_LR, "STAD LRIs" = stad_LR, "CRC LRIs" = crc_LR, "LUAD LRIs" = luad_LR)
dir.create("./suppl_files/")
write.xlsx(list_of_datasets, file = "./suppl_files/Supplementary File 7 - LRI List.xlsx")
```

```{r}
sessionInfo()
```
